#!/usr/bin/env python3
import sys
import i3ipc


ipc = i3ipc.Connection()

focused = ipc.get_tree().find_focused()
marks = focused.marks
targets = sys.argv[1:]

if len(targets) < 1:
    sys.exit(1)

def rotate(mark):
    index = sys.argv[1:].index(mark)
    next_mark = targets[(index + 1) % len(targets)]
    ipc.command(f"[con_mark={next_mark}] focus")


for mark in marks:
    if mark in targets:
        rotate(mark)
        sys.exit(0)
else:
    ipc.command(f'[con_mark="{targets[0]}"] focus')
    sys.exit(0)

sys.exit(1)
