#!/bin/env python3

""" this code will run when change focus in workspace """
import re
import sys
import i3ipc

def get_defaults(conn):
    regex = re.compile(r"^# workspace_default_layout (\d+) (\w+)$")
    version = conn.get_version();
    defaults = {}
    with open(version.loaded_config_file_name, 'r') as config:
        for line in config.readlines():
            m = regex.match(line)
            if m:
                print(f"[ ] {m.group(0)}")
                try:
                    ws = int(m.group(1))
                    layout = m.group(2)
                    defaults[ws] = layout
                except:
                    pass
    return defaults


# pylint: disable=invalid-name
i3 = i3ipc.Connection()

layouts = get_defaults(i3)

MANAGED_MARK = "MANAGED_WORKSPACE"

def set_web_layout_to_tab(workspace):
        """ because i3 do not support different layouts (stack, tabbed, split) on different
        workspaces dynamically. https://github.com/i3/i3/issues/531 """
        if workspace and workspace.num in layouts and len(workspace.nodes) > 1: # $ws_web. see ~/.config/i3/config
            if MANAGED_MARK not in workspace.marks:
                print(f"[!] Workspace {workspace.name} is now using {layouts[workspace.num]} layout")
                i3.command(f'[con_id="{workspace.id}"] mark --add {MANAGED_MARK}')
                i3.command(f'[con_id="{workspace.id}"] layout {layouts[workspace.num]}')



# pylint: disable=unused-argument
def on_window_focus(self, event):
    focused = i3.get_tree().find_focused()
    set_web_layout_to_tab(focused.workspace())
               
# pylint: disable=unused-argument
def on_workspace_focus(self, event):
        """ change web workspace to tabbed layout on focus """
        set_web_layout_to_tab(event.current)

try:
        i3.on('workspace::focus', on_workspace_focus)
        i3.on('window::focus', on_window_focus)
        i3.main()
except KeyboardInterrupt:
        pass
