#!/bin/env python3

""" this code will run when change focus in workspace """
import re
import sys
import i3ipc

def get_defaults(conn):
    regex = re.compile(r"^# workspace_default_layout (\d+) (\w+)$")
    version = conn.get_version();
    defaults = {}
    with open(version.loaded_config_file_name, 'r') as config:
        for line in config.readlines():
            m = regex.match(line)
            if m:
                try:
                    ws = int(m.group(1))
                    layout = m.group(2)
                    defaults[ws] = layout
                except:
                    pass
    return defaults


# pylint: disable=invalid-name
i3 = i3ipc.Connection()

layouts = get_defaults(i3)

def set_web_layout_to_tab(event):
        """ because i3 do not support different layouts (stack, tabbed, split) on different
        workspaces dynamically. https://github.com/i3/i3/issues/531 """
        if event.current and event.current.num in layouts: # $ws_web. see ~/.config/i3/config
            if len(event.current.nodes) == 0: # Skit if the workspace has children
                i3.command(f'[con_id="{event.current.id}"] layout {layouts[event.current.num]}')
                

# pylint: disable=unused-argument
def on_workspace_focus(self, event):
        """ change web workspace to tabbed layout on focus """
        set_web_layout_to_tab(event)

try:
        i3.on('workspace::focus', on_workspace_focus)
        i3.main()
except KeyboardInterrupt:
        pass
