#!/usr/bin/env python3

import i3ipc
import sys

ipc = i3ipc.Connection()

def focus(offset = 1):
    focused = ipc.get_tree().find_focused()
    workspace = focused.workspace()

    leaves = workspace.leaves()
    index = leaves.index(focused)

    window = leaves[(index + offset) % len(leaves)]

    window.command("focus")

def main(argv):
    if "next" in argv:
        focus(1)
    elif "prev" in argv:
        focus(-1)


if __name__ == "__main__":
    main(sys.argv[1:])

