#!/usr/bin/env python3

import argparse
import getopt
import i3ipc
import json
import sys
import os

parser = argparse.ArgumentParser(
    description="Mark / Float / Send or bring from Scratchpad"
)
parser.add_argument("-m", "--mark", action="store", help="Use this mark")

args = parser.parse_args()


con = i3ipc.Connection()

tree = con.get_tree()
marked = tree.find_marked(f"^({args.mark})$")
focused = tree.find_focused()
scratch = tree.scratchpad().leaves()

if len(marked):
    if marked[0] in scratch:
        marked[0].command("floating disable, floating enable, focus")
    else:
        marked[0].command("move scratchpad")
else:
    if "on" in focused.floating:
        focused.command(f"mark --add {args.mark}")
        focused.command(f"move scratchpad")

