#! /usr/bin/env python3

import i3ipc, argparse

# Initialises the argument parser
parser = argparse.ArgumentParser(
    description="Pops out a tiled window into a floating window in the same place"
)

# Adds the --sticky option
sticky_parser = parser.add_mutually_exclusive_group(required=False)
sticky_parser.add_argument("--sticky", dest="stick", action="store_true")
sticky_parser.set_defaults(stick=False)
args = parser.parse_args()
sticky = bool(args.stick)

i3 = i3ipc.Connection()

focused = i3.get_tree().find_focused()

windowWidth, windowHeight, windowX, windowY = (
    str(focused.rect.width),
    str(focused.rect.height),
    str(focused.rect.x),
    str(focused.rect.y),
)

float_window = focused.command(f"floating enable")
move_window = focused.command(f"move absolute position {windowX} {windowY}")
resize_window = focused.command(f"resize set {windowWidth} {windowHeight}")

if sticky:
    tick_window = focused.command("sticky toggle")
