#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ts=4 sts=4 sw=4 et ai

# Put this in /lib/udev/rules.d/69-backlight.rules:
#
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

import sys
import math
from subprocess import check_output, call

max_brightness = int(open('/sys/class/backlight/intel_backlight/max_brightness', 'r').read())
current_brightness = int(open('/sys/class/backlight/intel_backlight/brightness', 'r').read())

current_percent = math.ceil((current_brightness / float(max_brightness)) * 100)

step = int(sys.argv[1])

set_percent = current_percent + step
if set_percent > 100:
    set_percent = 100
elif set_percent < 20:
    set_percent = 20

if set_percent >= 30:
    print(int(math.ceil(max_brightness * (set_percent/100))))
    f = open('/sys/class/backlight/intel_backlight/brightness', 'w')
    f.write(str(int(math.ceil(max_brightness * (set_percent/100)))))
    f.close()

call(['notify-send', \
    '-h', 'string:synchronous:brightness',
    '-h', 'int:value:{}'.format(set_percent),
    '-u', 'low',
    'Setting brightness'])
