#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ts=4 sts=4 sw=4 et ai

# Put this in /lib/udev/rules.d/69-backlight.rules:
#
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

import sys
import math
from subprocess import check_output, call


call(['brightnessctl', 's', sys.argv[1]])

set_percent = check_output(['brightnessctl', 'i', '-m']).decode('utf-8')
set_percent = set_percent.split(',')[3]

call(['notify-send', \
    '-h', 'string:synchronous:brightness',
    '-h', 'int:value:{}'.format(set_percent),
    '-u', 'low',
    'Setting brightness'])
