#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ts=4 sts=4 sw=4 et ai

import i3ipc

i3 = i3ipc.Connection()
focused = i3.get_tree().find_focused()
ws = focused.workspace().name
if ':' in ws:
    ws = ':'.join(ws.split(":")[1:])

print("{}: {}".format(ws, focused.name))
