#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ts=4 sts=4 sw=4 et ai

import i3ipc

i3 = i3ipc.Connection()

focused = i3.get_tree().find_focused()
w = focused.workspace()

width = 320
height = 200


i3.command("border pixel 1")
i3.command("resize set {} {}".format(width, height))
i3.command("move position {} px {} px".format(w.rect.width-focused.rect.width,
    w.rect.height-focused.rect.height+17))
focused.rect.width = 200
