#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
set -a
. "${HOME}/.cache/wal/colors.sh"
set +a

reload_dunst() {
    envsubst < ~/.config/i3/dunst/dunstrc > ~/.config/i3/dunst/dunstrc.env
    pkill dunst
    dunst -config ~/.config/i3/dunst/dunstrc.env &
}

reload_dunst

