#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
set -a
. "${HOME}/.cache/wal/colors.sh"
set +a

is_systemd() {
    systemctl is-enabled --user "${1}" >/dev/null 2>&1
}

reload_dunst() {
    envsubst < ~/.config/dunst/dunstrc.env > ~/.config/dunst/dunstrc

    if is_systemd dunst; then
        systemctl --user restart dunst
    elif is_systemd user-dunst; then
        systemctl --user restart user-dunst
    else
        echo "(Re)starting manually"
        pkill dunst
        nohup dunst -config ~/.config/i3/dunst/dunstrc >/dev/null 2>&1 &
    fi
}

reload_dunst

