#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
set -a
. "${HOME}/.cache/wal/colors.sh"
set +a

is_systemd() {
    systemctl status --user dunst >/dev/null 2>&1
}

reload_dunst() {
    envsubst < ~/.config/dunst/dunstrc.env > ~/.config/dunst/dunstrc

    if is_systemd; then
        echo "(Re)starting via systemd"
        systemctl restart --user dunst
    else
        echo "(Re)starting manually"
        pkill dunst
        nohup dunst -config ~/.config/i3/dunst/dunstrc.env >/dev/null 2>&1 &
    fi
}

reload_dunst

