#!/bin/bash
set -euf -o pipefail

PASSWORD=$(pwgen 128 1);
TEMP=$(mktemp -d);
ARCHIVE="${TEMP}/out.zip"

function rm_temp_at_exit() {
    rm -fr "${TEMP}"
}
trap rm_temp_at_exit EXIT

zip -9 -r -P"${PASSWORD}" "${ARCHIVE}" "$@"

URL="$(cat "${ARCHIVE}" | base64 | ~/.bin/ix)"

if [[ -n "${URL}" ]]; then
    echo "Upload successful !"
    echo "To download on the target host:"
    echo "wget -O- '$URL' | base64 -d > out.zip && unzip -P'${PASSWORD}' out.zip"
fi
