#!/bin/bash
set -eu -o pipefail

pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
while([ -h "${SCRIPT_PATH}" ]); do
    cd "`dirname "${SCRIPT_PATH}"`"
    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
done
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH="`pwd`";
popd  > /dev/null

pushd "${SCRIPT_PATH}/../../" >/dev/null

_process_templates() {
	while IFS= read -r -d '' line; do 
		line="${line#*/}"
		line="${line%.*}"
		echo "[*] Processing: ${HOME}/${line}"
		~/.bin/jinja-config-templater ~/${line} || true
    	done
}


process_templates() {
	module="${1}"
	find "${module}/" \( -type f -o -type l  \) -iname '*.tpl' -print0 | _process_templates
}


process_dependencies() {
	module="${1}"
	case "${module}" in
		themes)
			update-custom-gtk-theme
			process_templates "${module}"
			;;
		i3)
			i3-config-templater
			process_templates "${module}"
			;;
        neovim)
			process_templates "${module}"
            nvim +PlugInstall +PlugClean +qall
            ;;
		*)
			process_templates "${module}"
			;;
	esac
}


stow stow
process_templates stow

# Copy post checkout script (not copied by stow)
cp -f ~/.local/dotfiles/git-hooks/post-checkout .git/hooks/post-checkout

if [ -n "${1-}" -a -f ~/.config/dotfiles/${1-} ]; then
	stow "${1}"
	process_dependencies "${1}"
	exit 0
fi

for i in ~/.config/dotfiles/*; do
	module="$(basename "${i}")"
	stow "${module}"
	process_dependencies "${module}"
done
