#!/bin/bash


for i in /usr/bin/virtualenvwrapper.sh \
	/usr/share/virtualenvwrapper/virtualenvwrapper.sh; do

    if [ -f "${i}" ]; then
	    wrapper="${i}"
	    break
    fi
done

[ -f "${wrapper}" ] && source "${wrapper}" || exit 1

set -o pipefail
shopt -s nullglob

venv_name() {
    echo -n "$(basename "$(dirname "${1}")")"
}

for req in ~/.virtualenvs/*/requirements-py3.txt; do
    env=$(venv_name "${req}")
    echo "[creating] ${env}:python3"
    mkvirtualenv -p /usr/bin/python3 "${env}" >/dev/null || true
    workon "${env}"
    pip3 install -r "${req}" "${@}"
    deactivate
done

for req in ~/.virtualenvs/*/requirements-py2.txt; do
    env=$(venv_name "${req}")
    echo "[creating] ${env}:python2"
    mkvirtualenv -p /usr/bin/python2 "${env}" >/dev/null || true
    workon "${env}"
    pip2 install -r "${req}" "${@}"
    deactivate
done
